### ISSUE TITLE
Потеря редактируемых данных

### ISSUE THREAD

**Issue by padlyuck** [yarkovaleksei/toster-wysiwyg-panel#14]
При включенном автообновлении ответов пропадает форма редактирования ответа.
1. Пишем ответ на вопрос и опубликовываем его.
2. Нажимаем отредактировать ответ и ждем указанное в настройках расширения время
3. Форма исчезает, а вместе с ней и те изменения которые мы хотели внести в ответ.
Баг воспроизводится только при редактировании ответа. С созданием нового таких проблем нету

**Comment by yarkovaleksei** [comment]
Хм... Да. С комментариями я это учел, а вот тут упустил. Спасибо за сигнал.
