### ISSUE TITLE
Добавить отслеживание новых вопросов

### ISSUE THREAD

**Issue by yarkovaleksei** [yarkovaleksei/toster-wysiwyg-panel#4]
Нужно добавить отслеживание новых вопросов в ленте.

Например, если находишься на странице [https://toster.ru/my/feed](https://toster.ru/my/feed), то средствами AJAX надо отследить новые вопросы и если они есть, обновить список без перезагрузки страницы.

**Comment by padlyuck** [comment]
было бы круто еще и на иконке расширения их как-то отображать для тех случаев когда на сайте не сидишь

**Comment by yarkovaleksei** [comment]
На иконке отображается количество непрочитанных уведомлений
