### ISSUE TITLE
Необходимо запоминать показанные с помощью Notification API уведомления

### ISSUE THREAD

**Issue by delphinpro** [yarkovaleksei/toster-wysiwyg-panel#7]
Т.е. показали один раз и хватит. Сейчас плашка выскакивает бесконечно, каждые 5-10 сек, пока на тостере не просмотришь всё.

**Comment by yarkovaleksei** [comment]
Принято. Действительно, что-то я затупил :smiley:

**Comment by yarkovaleksei** [comment]
@delphinpro а не подскажешь по какому критерию запоминать? По ID вопроса (пока трудно реализовать) или еще как? Просто не могу понять как мне флаг выставить показывать/не показывать плашку.
